<?php

require_once('../app/bootstrap.php');

/*$template->loads('main/header', array(
    'title' => 'Loja - Página Inicial'
));
*/
//session_name('admin');
if(!$_SESSION['logado']) {
    if(empty($_REQUEST)) {
        header("Location: login.php");
    } 
    header("Location: login.php?i=0");
}
?>
<div class="container">
    <div class="row">
        
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="../clientes/editar.php" class="btn btn-info">Novo Cliente</a>
                    <a href="../clientes/" class="btn btn-success">Ver todos</a>
                </div>
                <div class="panel-body">
                    <form action="../clientes/actions.php" method="post">
                        <label>Pesquisar pelo Cpf: </label>&nbsp;
                        <input type="text" name="search_cpf" 
                            onblur="javascript: validarCPF(this.value);" 
                            onkeypress="javascript: mascara(this, cpf_mask);" 
                            maxlength="14" required>&nbsp;
                        <button type="submit" class="btn btn-warning" >Pesquisar</button>
                    </form>
                </div>
                <div class="panel-body">
                    <form action="../clientes/" method="post">
                        <label>Pesquisar por Nome: </label>
                        <input type="text" name="search_name" required>
                        <button type="submit" class="btn btn-warning" >Pesquisar</button>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <label><span>Requisições de Produtos</span></label><?= $espaco2?>
                    <a href="../produtos/requests.php" class="btn btn-success">Ver todos</a>
                </div>
                <div class="panel-body">
                    <form action="../produtos/action.php?req=1&new=1" method="post" class="form">
                        <input type="text" name="product_requisition" size="50" placeholder='Digite uma nova solicitacao de produto' required>
                        <br><br><?= $espaco2.$espaco0?>
                        <button class="btn btn-info">Nova Requisicao de Produto</button>
                    </form>
                </div>
            </div>

        </div>


        <div class="col-md-6">
        <div class="panel panel-default">
        <div class="panel-heading">
            <a href="../produtos/cadastra.php" class="btn btn-info">Novo Produto</a>
            <a href="../produtos/" class="btn btn-success">Ver Todos</a>
            <a href="../produtos/?e=1" class="btn btn-success">Com Estoque</a>
            <a href="../produtos/?e=0" class="btn btn-danger">Sem Estoque</a>
        </div>
        <div class="panel-body">
            <form class="form" action="../produtos/?sku=1" method="post">
              <div class="form-group">
                <label>Pesquisar por código</label>
                <input class="form-control" type="text" name="codigo" placeholder="Digite o Código" required>
              </div>
              <div class="form-group">
                <button type="submit" class="btn btn-warning" >Pesquisar</button>
              </div>
            </form>
            <form class="" action="../produtos/?c=1" method="post">
                <label>Produtos por Categoria: </label>
                <div class="form-group">
                    <select class="form-control" name="onlycat">
                    <option>Selecione a Categoria</option>
                    <?php foreach($categoriasALL as $cat => $key):
                        echo "<option value='$key'> $cat </option>";
                    endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-warning" >Pesquisar</button>
                </div>
            </form>
        </div>
        </div>
        </div>
        
    </div>
</div>
</body>