<?php

require_once('../app/bootstrap.php');


?>
    <div class="container">
        <div class="page-header">
          <h1>Produtos <small>Total de produtos cadastrados: <?php echo $qtd_produtos; ?></small></h1>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Produto</th>
                    <th>Código</th>
                    <th>Categoria</th>
                    <th>Genero</th>
                    <th>Estoque</th>
                    <th>Valor Custo</th>
                    <th>Valor Venda</th>
                    <th>Detalhes</th>
                    <th>Observacoes</th>
                    <th>Ações</th>
                </tr>
                </thead>

        <?php
        	foreach($produtos as $key => $dados):
            	extract($dados);
        ?>
            <tbody>
                <tr>
                <td><?php echo normalize($nome); ?></td>
                <td><?php echo $codigo; ?></td>
                <td><?php echo $categoria; ?></td>
                <td><?php echo $genero; ?></td>
                <td><?php echo $estoque_geral; ?></td>
                <td><?php echo $vlr_custo; ?></td>
                <td><?php echo $vlr_venda; ?></td>
                <td><?php echo $detalhes; ?></td>
                <td><?php echo $observacoes; ?></td>
                <td><a href="editar.php?id=<?php echo $key; ?>"  class="btn btn-info">Editar</a>&nbsp;&nbsp;&nbsp;
                <a href="action.php?a=<?php echo $key; ?>"  class="btn btn-danger">Apagar</a></td>
                </tr>
            </tbody>
        <?php endforeach; ?>

            </table>
        </div>
    <br>
        <a href="produtos/cadastra?p=1" class="btn btn-success">Novo Produto</a>
        </div>
